import pandas as pd
import argparse
import os
from pathlib import Path

LABELS = [
    "Change Variable Type",
    "Change Parameter Type",
    "Change Return Type",
    "Extract Method",
    "Move Method",
    "Rename Method",
    "Rename Variable",
    "Rename Parameter",
    "Extract Variable",
    "Add Parameter"
]

def label_dataset(designite_p, matches_p, output_p):
    if not os.path.exists(designite_p) or not os.path.exists(matches_p):
        print("Error: Input files not found.")
        return

    project_name = Path(designite_p).stem
    output_path = Path(output_p)

    if output_path.is_dir() or str(output_p).endswith(('\\', '/')):
        output_path = output_path / f"{project_name}_labeled.csv"

    output_path.parent.mkdir(parents=True, exist_ok=True)

    print("--- Loading Data ---")
    df_designite = pd.read_csv(designite_p)
    df_designite.columns = df_designite.columns.str.strip()
    
    df_matches = pd.read_csv(matches_p)

    # Dynamically locate columns for File, Method, and Line because different Designite 
    # execution formats output slightly different column headers.
    col_map = {}
    for c in ['File', 'File Path']:
        if c in df_designite.columns: col_map['file'] = c; break
    for c in ['Method Name', 'Method', 'Member']:
        if c in df_designite.columns: col_map['method'] = c; break
    for c in ['Line', 'Line no', 'Line No', 'Start Line']:
        if c in df_designite.columns: col_map['line'] = c; break

    if not all(k in col_map for k in ['file', 'method', 'line']):
        print("Error: File, Method, or Line columns not found in Designite.")
        return

    for label in LABELS:
        df_designite[label] = 0

    print("--- Building Refactoring Map ---")
    ref_map = {}
    
    for _, row in df_matches.iterrows():
        raw_path = str(row.get('File', '')).replace('\\', '/')
        m_name = str(row.get('method', 'N/A'))
        
        raw_line = row.get('Line no')
        m_line = int(raw_line) if pd.notna(raw_line) and str(raw_line).strip() else -1
        
        ref_type = str(row.get('refactoring', ''))
        
        if ref_type in LABELS:
            key = (raw_path, m_name, m_line)
            if key not in ref_map:
                ref_map[key] = set()
            ref_map[key].add(ref_type)

    matches_applied = 0
    rows_modified = 0
    total_rows = len(df_designite)

    print("--- Labeling Dataset ---")
    
    for idx, row in df_designite.iterrows():
        print(f"\rProcessing row {idx + 1}/{total_rows}...", end="", flush=True)

        d_path = str(row.get(col_map['file'], '')).replace('\\', '/')
        d_method = str(row.get(col_map['method'], 'N/A'))
        
        d_raw_line = row.get(col_map['line'])
        d_line = int(d_raw_line) if pd.notna(d_raw_line) and str(d_raw_line).strip() else -1
        
        key = (d_path, d_method, d_line)
        
        if key in ref_map:
            for ref_name in ref_map[key]:
                df_designite.at[idx, ref_name] = 1
                matches_applied += 1
            rows_modified += 1

    df_designite.to_csv(output_path, index=False)

    print("\n\n" + "="*40)
    print("LABELING COMPLETED")
    print(f"Total Designite Dataset rows: {total_rows}")
    print(f"Unique methods in matches.csv: {len(ref_map)}")
    print(f"Designite rows modified: {rows_modified}")
    print(f"Total '1' labels applied: {matches_applied}")
    print("="*40)
    print(f"[OK] File saved to: {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--designite', required=True, help="Path to the original Designite CSV file")
    parser.add_argument('--matches', required=True, help="Path to the matches_*.csv file generated by the previous script")
    parser.add_argument('--out', default='results/', help="Path to the final supervised CSV or directory")
    args = parser.parse_args()
    
    # Four parents up from project_thesis/src/core/labeller.py to get DesigniteJava/
    BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
    def resolve(p):
        path = Path(p)
        return path if path.is_absolute() else (BASE_DIR / path).resolve()

    label_dataset(str(resolve(args.designite)), str(resolve(args.matches)), str(resolve(args.out)))
